apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: todoapp:k8s.nginx.org/VirtualServer:todo/{{ include "todoapp.fullname" . }}-vs
  name: {{ include "todoapp.fullname" . }}-vs
  namespace: {{ $.Values.Namespace }}
  labels:
    app: {{ include "todoapp.fullname" . }}

spec:
  host: {{ .Values.virtualServer.host }}

  routes:
    {{/* -------- API ROUTES -------- */}}
    {{- if and .Values.apps .Values.apps.api .Values.apps.api.services }}
    {{- range .Values.apps.api.services }}
    - path: {{ .path }}
      action:
        proxy:
          upstream: {{ .name }}
          rewritePath: /
    {{- end }}
    {{- end }}

    {{/* -------- UI ROUTES -------- */}}
    {{- if and .Values.apps .Values.apps.ui .Values.apps.ui.services }}
    {{- range .Values.apps.ui.services }}
    - action:	
        proxy:	
          rewritePath: /	
          upstream: {{ .name }}
      path: {{ .path }}
    {{- end }}
    {{- end }}

  upstreams:
    {{/* -------- API UPSTREAMS -------- */}}
    {{- if and .Values.apps .Values.apps.api .Values.apps.api.services }}
    {{- range .Values.apps.api.services }}
    - name: {{ .name }}
      service: {{ .name }}
      port: 80
    {{- end }}
    {{- end }}

    {{/* -------- UI UPSTREAMS -------- */}}
    {{- if and .Values.apps .Values.apps.ui .Values.apps.ui.services }}
    {{- range .Values.apps.ui.services }}
    - name: {{ .name }}
      service: {{ .name }}
      port: 80
    {{- end }}
    {{- end }}
