apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: {{ include "todoapp.fullname" . }}-vs
  namespace: {{ $.Values.Namespace }}
  labels:
    app: {{ include "todoapp.fullname" . }}

spec:
  host: {{ .Values.virtualServer.host }}

  routes:
    {{/* -------- API ROUTES -------- */}}
    {{- if and .Values.apps .Values.apps.api .Values.apps.api.services }}
    {{- range .Values.apps.api.services }}
    - path: {{ .path }}
      route: {{ .name }}   # chỉ dùng tên upstream
    {{- end }}
    {{- end }}

    {{/* -------- UI ROUTES -------- */}}
    {{- if and .Values.apps .Values.apps.ui .Values.apps.ui.services }}
    {{- range .Values.apps.ui.services }}
    - path: {{ .path }}
      route: {{ .name }}   # chỉ dùng tên upstream
    {{- end }}
    {{- end }}

  upstreams:
    {{/* -------- API UPSTREAMS -------- */}}
    {{- if and .Values.apps .Values.apps.api .Values.apps.api.services }}
    {{- range .Values.apps.api.services }}
    - name: {{ .name }}
      service: {{ .name }}
      namespace: {{ $.Values.Namespace }}
      port: 80
    {{- end }}
    {{- end }}

    {{/* -------- UI UPSTREAMS -------- */}}
    {{- if and .Values.apps .Values.apps.ui .Values.apps.ui.services }}
    {{- range .Values.apps.ui.services }}
    - name: {{ .name }}
      service: {{ .name }}
      namespace: {{ $.Values.Namespace }}
      port: 80
    {{- end }}
    {{- end }}
